name: Publish on dockerhub

on:
    push:
        tags:
            - '*'

jobs:
    docker-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              run: |
                  printf ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
                  TAG=$(git describe --tags --always)
                  echo TAG=${TAG##v} >> $GITHUB_ENV
            - name: Build and push
              run: |
                  docker build -t ethersphere/swarm-gateway:${TAG} .
                  docker push ethersphere/swarm-gateway:${TAG}
