name: Test Settings

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - '**'

jobs:
    test-settings-strict:
        runs-on: ubuntu-latest
        services:
            mariadb:
                image: mariadb:10.5
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test_db
                    MYSQL_USER: test_user
                    MYSQL_PASSWORD: test_pass
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/setup-env

            - name: Insert instance
              run: |
                  mysql -h 127.0.0.1 -u test_user -ptest_pass test_db -e "
                    INSERT INTO settings (name, defaultWebsiteRule, defaultFileRule, defaultEnsRule, redirectUri) VALUES
                      ('strict', 'deny', 'deny', 'deny', '')
                    ;
                  "

            - name: Run gateway
              run: |
                  export INSTANCE_NAME="strict"
                  export DATABASE_PASSWORD="test_pass"
                  export DATABASE_CONFIG="{\"user\":\"test_user\",\"database\":\"test_db\"}"
                  export TEMPORARY=5
                  export BEE_API_URL=http://localhost:16337
                  node dist > gateway.log 2>&1 < /dev/null &

            - name: Expect HTTP 302 for file
              run: npx npxie code-equals http://localhost:3000/bzz/f000000000000000000000000000000000000000000000000000000000000000 302

            - name: Expect HTTP 302 for website
              run: npx npxie code-equals http://localhost:3000/bzz/1000000000000000000000000000000000000000000000000000000000000000 302

            - name: Expect HTTP 302 for .eth
              run: npx npxie code-equals http://localhost:3000/bzz/arbitrary.eth 302

    test-settings-permissive:
        runs-on: ubuntu-latest
        services:
            mariadb:
                image: mariadb:10.5
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test_db
                    MYSQL_USER: test_user
                    MYSQL_PASSWORD: test_pass
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/setup-env

            - name: Insert instance
              run: |
                  mysql -h 127.0.0.1 -u test_user -ptest_pass test_db -e "
                    INSERT INTO settings (name, defaultWebsiteRule, defaultFileRule, defaultEnsRule, redirectUri) VALUES
                      ('permissive', 'allow', 'allow', 'allow', '')
                    ;
                  "

            - name: Run gateway
              run: |
                  export INSTANCE_NAME="permissive"
                  export DATABASE_PASSWORD="test_pass"
                  export DATABASE_CONFIG="{\"user\":\"test_user\",\"database\":\"test_db\"}"
                  export TEMPORARY=5
                  export BEE_API_URL=http://localhost:16337
                  node dist > gateway.log 2>&1 < /dev/null &

            - name: Expect HTTP 200 for file
              run: npx npxie code-equals http://localhost:3000/bzz/f000000000000000000000000000000000000000000000000000000000000000 200

            - name: Expect HTTP 200 for website
              run: npx npxie code-equals http://localhost:3000/bzz/1000000000000000000000000000000000000000000000000000000000000000 200

            - name: Expect HTTP 200 for .eth
              run: npx npxie code-equals http://localhost:3000/bzz/arbitrary.eth 200

    test-redirect-uri:
        runs-on: ubuntu-latest
        services:
            mariadb:
                image: mariadb:10.5
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: test_db
                    MYSQL_USER: test_user
                    MYSQL_PASSWORD: test_pass
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/setup-env

            - name: Insert instance
              run: |
                  mysql -h 127.0.0.1 -u test_user -ptest_pass test_db -e "
                    INSERT INTO settings (name, defaultWebsiteRule, defaultFileRule, defaultEnsRule, redirectUri) VALUES
                      ('main', 'deny', 'allow', 'allow', 'https://bzz.limo')
                    ;
                  "

            - name: Run gateway
              run: |
                  export INSTANCE_NAME="main"
                  export DATABASE_PASSWORD="test_pass"
                  export DATABASE_CONFIG="{\"user\":\"test_user\",\"database\":\"test_db\"}"
                  export TEMPORARY=5
                  export BEE_API_URL=http://localhost:16337
                  node dist > gateway.log 2>&1 < /dev/null &

            - name: Expect absolute redirect URI
              run: npx npxie 3xx http://localhost:3000/bzz/1000000000000000000000000000000000000000000000000000000000000000 https://bzz.limo/forbidden?hash=1000000000000000000000000000000000000000000000000000000000000000
